apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels: 
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name : {{ .Values.app.name }}
        image: {{ .Values.app.imageURL }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: mongoURL
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongo-uri
        resources: 
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}