apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source: 
    repoURL:  'git@gitlab.com:baryvee/portfolio-gitops.git'
    targetRevision: HEAD
    path: app/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
      automated:
        selfHeal: true