apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: promstack
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: 
  project: default
  source: 
    chart:  kube-prometheus-stack
    repoURL:  https://prometheus-community.github.io/helm-charts
    targetRevision: 41.7.3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
      automated:
        selfHeal: true