FROM python:3.8.2-slim-buster

WORKDIR /app
COPY app.py /app/
COPY templates /app/templates/
COPY requirements.txt /app/

ENV mongoURL="mongodb://root:example@mongodb:27017/"

RUN pip install -r requirements.txt

ENTRYPOINT ["python","app.py"]